### PR TITLE
Fix millis() and micros() rollover bug

### PR DESCRIPTION
**Pull request by Lauszus**
* Fix millis() and micros() rollover bug
* Explicit cast millis() and micros() to uint32_t, as it is uint64_t on the Arduino 101
* Use fixed width integer types, so it is not architecture dependent

See: https://github.com/felis/USB_Host_Shield_2.0/issues/285#issuecomment-279200128

@YuuichiAkagawa and @mattomatto can you guys test this?

### CODE REVIEW

**Comment by YuuichiAkagawa** [comment]
Is Arduino 101 also good for this? Is it unnecessary to cast a return value?

**Comment by Lauszus** [comment]
@YuuichiAkagawa actually we should probably cast millis() and micros() to ```uint32_t``` at every location, since it is ```uint64_t``` on the Arduino 101.

**Comment by Lauszus** [comment]
@YuuichiAkagawa please also see: https://github.com/felis/USB_Host_Shield_2.0/pull/289/commits/42948831ce92c51a94c5175c063946cf61d04ea5 and https://github.com/felis/USB_Host_Shield_2.0/pull/289/commits/5ba28d186f3021132cde4bf6c9dfb856a68dda85.

**Comment by Lauszus** [comment]
@YuuichiAkagawa did you ever have time to test this?

**Comment by YuuichiAkagawa** [comment]
OK, I will test this weekend. 😃

**Comment by Lauszus** [comment]
@YuuichiAkagawa thank you!

**Comment by YuuichiAkagawa** [comment]
## Test results
|                        |UNO|Leonardo|101|Due|Teensy3.2|
|:-----------------------|:-:|:------:|:-:|:-:|:-------:|
|USB_Desc                |o  |o       |o  |o  |o        |
|hub_demo                |o  |o       |o  |o  |o        |
|USBH_MIDI_dump          |o  |o       |o  |o  |o        |
|USB_MIDI_converter      |o  |o       |o  |o  |o        |
|USB_MIDI_converter_multi|o  |o       |o  |o  |o        |
|bidrectional_converter  |o  |o       |o  |o  |o        |
|eVY1_sample             |o  |o       |o  |o  |o        |

Normal operation is OK.

The rollover case has not been completed yet. This test takes 70 minutes to run. Do you have any idea?

**Comment by YuuichiAkagawa** [comment]
LGTM 👍 
MIDI test is done. Other devices is review only.

**Comment by Lauszus** [comment]
> The rollover case has not been completed yet. This test takes 70 minutes to run. Do you have any idea?

I'm not sure what you mean? Does it hang?

**Comment by YuuichiAkagawa** [comment]
> I'm not sure what you mean? Does it hang?
No, no. micros() takes 70 minutes to overlap. I'ts too long to test. 😢

**Comment by Lauszus** [comment]
@YuuichiAkagawa can't you just leave it running?

**Comment by YuuichiAkagawa** [comment]
@Lauszus 
70 min * 4 platform = 280 min = 4.6 hrs.
I just wanted to know if there was a way to do the tests efficiently.

As a result the test is complete so there is no problem.

**Comment by xxxajk** [comment]
Salt the calculation by adding to it thus causing early rollover.
Just modify millis() temporarily in the hardware config, and add enough to
cause a rollover in 30 seconds (or something else).

**Comment by Lauszus** [comment]
@YuuichiAkagawa so everything is to merge, right?

**Comment by YuuichiAkagawa** [comment]
@Lauszus 
Yes. USB Host, hub and MIDI are OK.

**Pull request merged**
