### PR TITLE
Store rumble value in local buffer, so the rumble is not affected whe…

### LINKED ISSUE #186: PS3BT: setLed will activate last rumble action
I have found that setLedOn, setLedOff, and setLedToggle all have the side effect of triggering whatever the last rumble action was.

I have included a basic sketch that calls the setRumbleON function upon the connection of a PS3 controller.
Pressing select, PS, or start will call each of the different setLed functions.

I am using an Arduino Mega ADK r3 with an Azio BTD-V201 dongle to connect the sony sixaxis controller.

```
#include <PS3BT.h>
#include <usbhub.h>

int newconnect = 0;
USB Usb;
USBHub Hub1(&Usb);
BTD Btd(&Usb);
PS3BT PS3(&Btd);

void setup() {
  Serial.begin(115200);
  if (Usb.Init() == -1)
  {
    Serial.print(F("\r\nOSC did not start"));
    while (1);
  }
  Serial.print(F("\r\nPS3 Bluetooth Library Started"));
}

void loop() {

  Usb.Task();

  if (PS3.PS3Connected)
  {
    if (newconnect == 0)
    {
      newconnect++;
      Serial.println("Rumble is on!");
      PS3.setRumbleOn(100, 255, 100, 255); //VIBRATE!!!
    }

    if (PS3.getButtonClick(SELECT)) {
      PS3.setLedOn(LED2);
    }
    if (PS3.getButtonClick(START)) {
      PS3.setLedOff(LED1);
    }
    if (PS3.getButtonClick(PS)) {
      PS3.setLedToggle(LED3);
    }
  }
}
```

### PR DESCRIPTION
**Pull request by Lauszus**
…n setting the LEDs

Fixes #186

### CODE REVIEW

**Comment by matt-bull** [comment]
Rumble and setLed no longer function.

**Comment by Lauszus** [comment]
@matt-bull can you share a minimal example please?

**Comment by Lauszus** [comment]
@matt-bull I had swapped the destination and source buffer, sorry. Please try the code again.

**Comment by matt-bull** [comment]
@Lauszus Sorry I didn't get back to you yesterday. It does appear that the rumble and set led functions now work as expected! Thanks!

**Comment by Lauszus** [comment]
@matt-bull thanks for testing and submitting the issue :)

**Pull request merged**
