### PR TITLE
Added support for Teensy 3.5 and 3.6

### PR DESCRIPTION
**Pull request by Lauszus**
See: #270

### CODE REVIEW

**Comment by Lauszus** [comment]
@BlueGene00 could you please test this?

**Comment by BlueGene00** [comment]
@Lauszus Just tested the changes and it seems to work without any issues or errors.

I have only tested with a Teensy 3.6 and checked, if the PS4-controller-library works. If you want further tests, please let me know what to do.

**Comment by Lauszus** [comment]
No that's fine. Thank you for testing it!

**Comment by Lauszus** [comment]
@ivankravets did you change how the library dependencies are found in PlatformIO recently? The Travis build for the merge failed: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/182081048#L485-L487, while it passed all checks when I committed it 11 days ago: https://travis-ci.org/felis/USB_Host_Shield_2.0/builds/179154980.

I have tried to delete the cache on Travis and restart the build, but that did not help.

**Comment by Lauszus** [comment]
It looks like it might be a bug in 3.2.0: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/182081048#L193, as it worked with 3.1.0: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/179154981#L191.

**Comment by ivankravets** [comment]
@Lauszus We have just released new PIO Core 3.2 with built-in Python-based C Preprocessor. Now, it evaluates your code while searches dependencies. As result, [this line](https://github.com/felis/USB_Host_Shield_2.0/blob/master/usbhost.h#L25) fails. 

There are few correct solutions:

1. Specify build flag `-DUSING_SPI4TEENSY3` for a project where do you need this library
2. Or add [here](https://github.com/felis/USB_Host_Shield_2.0/blob/master/.travis.yml#L66) `-DUSING_SPI4TEENSY3`

**Comment by ivankravets** [comment]
Here is a doc about PlatformIO Library Dependency Finder

* http://docs.platformio.org/en/stable/librarymanager/ldf.html

**Comment by Lauszus** [comment]
@ivankravets it is getting set here: https://github.com/felis/USB_Host_Shield_2.0/blob/master/settings.h#L133. Maybe this is failing: https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/Bluetooth/BTHID/BTHID.ino#L13?

**Comment by Lauszus** [comment]
And settings is included first: https://github.com/felis/USB_Host_Shield_2.0/blob/master/Usb.h#L27, so it should work.

**Comment by Lauszus** [comment]
It compiles fine in Arduino 1.6.12 as well.

**Comment by Lauszus** [comment]
Also the problem is that it can't find the library: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/182081048#L500 and not that the preprocessor.

**Comment by ivankravets** [comment]
@Lauszus I'm going to make hotfix release and revert back `chain` mode for LDF as default. I'll report here. Sorry.

**Comment by ivankravets** [comment]
@Lauszus Please clean cache and restart job. Thanks!

**Comment by Lauszus** [comment]
@ivankravets that fixed it. Thanks for your quick support as always!

**Comment by ivankravets** [comment]
@Lauszus Thank you that reported! I'll take a look at `chain+` mode behaviour using your library later.

**Comment by Lauszus** [comment]
@ivankravets sounds good :)

**Pull request merged**
