### PR TITLE
Fix NAK data corruption

### PR DESCRIPTION
**Pull request by gdsports**
See https://github.com/felis/USB_Host_Shield_2.0/issues/403

### CODE REVIEW

**Comment by Lauszus** [comment]
Looks good to me. @felis okay to merge?

**Comment by gdsports** [comment]
Hold off merging this because a different fix will make this unnecessary. Fixing #462 should also fix this problem. Both problems have the same root cause.

**Comment by xxxajk** [comment]
I have the patch, just waiting for credentials to push it.

**Comment by felis** [comment]
@Lauszus please do. Thanks everybody!

**Comment by gdsports** [comment]
Superceded by #473

**Pull request closed without merging**
