### PR TITLE
Continuous Integration with Travis.CI + PlatformIO

### PR DESCRIPTION
**Pull request by ivankravets**
More details http://docs.platformio.org/en/latest/ci/travis.html

P.S: @felis Please enable https://travis-ci.org for this project. It should look like https://travis-ci.org/ivankravets/USB_Host_Shield_2.0.

Comments are welcome!

### CODE REVIEW

**Comment by Lauszus** [comment]
I'm in favour of merging this. @felis and @xxxajk what do you say?

**Comment by felis** [comment]
I'm with you.

2015-05-22 16:38 GMT-06:00 Kristian Sloth Lauszus <notifications@github.com>
:

> I'm in favour of merging this. @felis <https://github.com/felis> and
> @xxxajk <https://github.com/xxxajk> what do you say?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/pull/152#issuecomment-104790089>
> .
>



-- 
/felis

**Comment by Lauszus** [comment]
Cool. I will merge it now then. Thanks @ivankravets :)

**Comment by felis** [comment]
thx!

2015-05-22 17:25 GMT-06:00 Kristian Sloth Lauszus <notifications@github.com>
:

> Merged #152 <https://github.com/felis/USB_Host_Shield_2.0/pull/152>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/pull/152#event-312140712>.
>



-- 
/felis

**Comment by Lauszus** [comment]
@felis it looks like you need to login to Travis: https://travis-ci.org/felis and then add the repository. If don't want to manage it, I can just change the owner to me: https://github.com/ivankravets/USB_Host_Shield_2.0/commit/89dd398ab1a07e122982571c76ad3e0a7a53ba16 and I will take care of it.

**Comment by Lauszus** [comment]
Hmm it looks like it has to be you.

**Comment by felis** [comment]
I got there but I don't understand what to do there. Are there any docs
anywhere?

2015-05-22 17:32 GMT-06:00 Kristian Sloth Lauszus <notifications@github.com>
:

> Hmm it looks like it has to be you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/pull/152#issuecomment-104801679>
> .
>



-- 
/felis

**Comment by Lauszus** [comment]
See step 1, 2, and step 4 here: http://docs.travis-ci.com/user/getting-started/.

**Comment by Lauszus** [comment]
Basically you need to:
1. Login
2. Add the repository
3. Make a git commit and push it.

**Comment by Lauszus** [comment]
A good commit, would be to add the rest of the example to https://github.com/felis/USB_Host_Shield_2.0/blob/master/.travis.yml ;)
Let me know if you want me to do that part.

**Comment by Lauszus** [comment]
Here is a command to get the full list of examples:
```bash
find . -type f  -name '*.ino' | awk '{ print "- PLATFORMIO_CI_SRC="$1 }' | sed 's/.\///'
```

**Comment by felis** [comment]
seems like I made it work - can you see anything?

2015-05-22 17:57 GMT-06:00 Kristian Sloth Lauszus <notifications@github.com>
:

> Here is a command to get the full list of examples:
>
> find . -type f  -name '*.ino' | awk '{ print "- PLATFORMIO_CI_SRC="$1 }' | sed 's/.\///'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/pull/152#issuecomment-104803801>
> .
>



-- 
/felis

**Comment by Lauszus** [comment]
Yep it's running: https://travis-ci.org/felis/USB_Host_Shield_2.0 :)

**Comment by Lauszus** [comment]
Hmm this job failed for some reason: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/63730447.

**Comment by felis** [comment]
nice.

2015-05-22 18:15 GMT-06:00 Kristian Sloth Lauszus <notifications@github.com>
:

> Yep it's running: https://travis-ci.org/felis/USB_Host_Shield_2.0 :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/pull/152#issuecomment-104805863>
> .
>



-- 
/felis

**Comment by felis** [comment]
i see that too, but there is no diagnostics. Hard to guess what's going on


2015-05-22 18:16 GMT-06:00 Kristian Sloth Lauszus <notifications@github.com>
:

> Hmm this job failed for some reason:
> https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/63730447.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/pull/152#issuecomment-104805896>
> .
>



-- 
/felis

**Comment by Lauszus** [comment]
It looks like their were a connection issue. I just made it run the job again.

**Comment by Lauszus** [comment]
I just added the rest of the examples as well: https://github.com/felis/USB_Host_Shield_2.0/commit/251efba57bd9d33a958081e12598123482893082.

**Comment by Lauszus** [comment]
Looks like there is a bug in Travis: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/63730963#L255.

**Comment by Lauszus** [comment]
It's complaining about this line: https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/adk/term_test/term_test.ino#L17.

**Comment by Lauszus** [comment]
@ivankravets it also looks like there is a bug in PlatformIO: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/63730966#L255-L260.

**Comment by Lauszus** [comment]
@ivankravets is it possible to define a value, so this can pass: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/63730974#L254-L255?

**Comment by Lauszus** [comment]
@ivankravets do we also need to add all header files to the environmental variables as well, so this will pass: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/63730981#L254?

**Comment by ivankravets** [comment]
Thanks a lot for feedback!

> It looks like their were a connection issue. I just made it run the job again.

PlatformIO keeps own packages on [PlatformIO Storage (sourceforge.net)](https://sourceforge.net/projects/platformio-storage/files/packages/). Sometimes @travis-ci has problem with connection to SourceForge.Net. If PlatformIO will be interesting for Continuous Integration from the other projects, I will ask @travis-ci to keep mirror of our packages within @travis-ci local network.

> it also looks like there is a bug in PlatformIO

@Lauszus Yes, I've just fixed a few bugs in PlatformIO ``*.ino`` to ``*.cpp`` converter. See https://github.com/platformio/platformio/commit/f732d4088b880d0d53d525fa349c4da50becb6f7. Also, I put to your ``.travis.yml`` temporary hook to use latest development version of PlatformIO. Please remove it when PlatformIO 2.0.1 will be released (or I will make new pull request with it). 

> do we also need to add all header files to the environmental variables as well

(http://docs.platformio.org/en/latest/userguide/cmd_ci.html#cmd-ci)[platformio ci] command has smart behaviour: if you pass "file to SRC", then PlatformIO will initialise new project with these files. However, if you pass "directory to SRC", then all files/dirs will be used as ``src`` directory. See this ``PLATFORMIO_CI_SRC=examples/acm/acm_terminal``

**Comment by ivankravets** [comment]
I've just pulled new request https://github.com/felis/USB_Host_Shield_2.0/pull/153 , where all examples are passed successfully except:

* adk_barcode.ino - https://travis-ci.org/ivankravets/USB_Host_Shield_2.0/jobs/63764686
* HID scale - https://travis-ci.org/ivankravets/USB_Host_Shield_2.0/jobs/63764707

See all builds: https://travis-ci.org/ivankravets/USB_Host_Shield_2.0

-------

As for 2 failed examples, I can' build them under Arduino IDE too.

**Comment by Lauszus** [comment]
@ivankravets I have just fixed the issue with the two examples. See: https://github.com/felis/USB_Host_Shield_2.0/commit/44d3b4a3223fc125b01370482b98e6f1ccbba370 and https://github.com/felis/USB_Host_Shield_2.0/commit/36056a40395d3b884ffe0562c223208563d8643f.

**Pull request merged**
