### PR TITLE
Switch to stable release of @PlatformIO

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by Lauszus** [comment]
Thanks!

**Comment by Lauszus** [comment]
@ivankravets has you considered hosting the files used by PlatformIO a different place? It's a bit annoying that I have to restart the Travis builds all the time.

**Comment by ivankravets** [comment]
@Lauszus sorry for the inconveniences. I've been working hardly on @PlatformIO reliability for a last few days. I'm with no worry as PlatformIO code, but we have a few 3-rd party projects/services which PlatformIO uses. SourceForge is in this list. I can't serve all this traffic with pre-built packages, it's ~1Gb (frameworks, toolchains, upload tools, SDKs, etc.). 

I've just made mirroring of all packages via ``dl.platformio.org`` and will redirect users to it when SF is off-line. See my commit https://github.com/platformio/platformio/commit/06baa98823db446298faabe4a8dbb51820dc34fb

P.S: Where do you have these problems with Travis restarting? In this repo?

**Comment by Lauszus** [comment]
@ivankravets thank you!

Yes I had to restart two of the sub-builds for this pull request.

**Comment by ivankravets** [comment]
I hope that the mirroring should avoid these problems. 

I've just created new pull-request https://github.com/felis/USB_Host_Shield_2.0/pull/155
I propose to use "develop" version for a while we wont have any problems within other projects.

P.S: If you have any problems with new ``develop`` @PlatformIO, please don't restart jobs, give me a link  with detailed log.

P.S.S: I see that we have problem with "ConnectionError" just with @travis-ci. The @circleci works without any problems.

**Comment by Lauszus** [comment]
@ivankravets here is a link to a build that has failed: https://travis-ci.org/felis/USB_Host_Shield_2.0/builds/64967160.

**Comment by ivankravets** [comment]
@Lauszus I fixed this error in PlatformIO 2.0.3 which has not been released yet. I made mirroring for PlatformIO packages, now it works good.

Nevertheless, I'll release 2.0.3 as soon as possible. Maybe, today. We have a few not closed issues which require to be tested by reporters https://github.com/platformio/platformio/milestones/2.0.3.

Sorry for this inconvenience.

**Comment by ivankravets** [comment]
@Lauszus please re-start time-outed jobs, I'll report here when PlatformIO 2.0.3 will be released. I hope that since 2.0.3 you will not have any problems in future. This high load/interest for PlatformIO is a new level for us. 

Currently, we aren't working on the new features, we are focused on improvements/bug fixes.

**Comment by Lauszus** [comment]
@ivankravets okay thanks :)

**Comment by ivankravets** [comment]
@Lauszus I've just [released PlatformIO 2.1.0](https://twitter.com/platformio_org/status/606152445165748224). I hope we wont have any problems with network access to PlatformIO packages in future.

Please report me about any broken jobs in future.

Have a nice coding! :blush:

**Comment by Lauszus** [comment]
@ivankravets thanks for getting back to me :) I will let you know if we have any issues.

**Pull request merged**
