### PR TITLE
Fix corruption. NEVER use SPI method transfer on a pointer.

### PR DESCRIPTION
**Pull request by xxxajk**
Should fix the problems.
Also removes duplicate code.

### CODE REVIEW

**Comment by gdsports** [comment]
The USBPrinter_uhs2 driver works with this patch using Uno and Leonardo. I do not have a Mega 2560 but the patch should work. Also the printer is confirmed to work on ESP8266. I will withdraw PR #470 since it is redundant.

BTW, M5Stack released a USB host MAX3421E module so I will be testing this out when I receive one. M5Stack is an ESP32 based system of stackable modules. The modules are like shields but include plastic casing so the module stack is professional looking.

https://m5stack.com/collections/m5-module/products/usb-module

**Comment by Lauszus** [comment]
Is this ready to merge?

**Comment by gdsports** [comment]
It has been working fine for me.

**Comment by Lauszus** [comment]
Thanks for the report @gdsports. I'll make a new release as well, so all the people that are using the Arduino library manager will get the update as well.

**Comment by Bacto** [comment]
Hi everyone ant thanks for this library :)
Do you have any news about the next release?
The last one is from 2018/15/03 and does not include this fix unfortunately :-/

**Comment by Vamshi253** [comment]
Hi @gdsports,

The USBPrinter_uhs2 driver is not working with this patch using Arduino Mega ADK. Could you please suggest any changes that I need to make in order to work out with Arduino Mega ADK.

Thank you

**Pull request merged**
