### PR TITLE
Make USBH work with new RedBear SDK for nRF51288

### PR DESCRIPTION
**Pull request by sieren**
@felis @Lauszus please review.

Had to make some changes to the gaming console classes in order to avoid collisions due to unscoped enums. If you have a better idea let me know.

### CODE REVIEW

**Comment by sieren** [comment]
Need to add some fixups to the examples (to get CI green)

**Comment by sieren** [comment]
Reping @felis @Lauszus

**Comment by xxxajk** [comment]
"LED" anything was a bad idea. 
Thankfully I've foreseen this sort of thing, and it won't be happening on UHS 3.0. 
Collisions like this will be a lot less likely, if not impossible...

**Comment by Lauszus** [comment]
@sieren thanks. Just merged your PR :)

**Pull request merged**
