### PR TITLE
Added support for the PS5 controller

### LINKED ISSUE #567: Help port PS5 controller support from SAMD fork
I recently got PS5 USB controller support working in the USB host shield SAMD fork (including the fancy trigger haptics), and it should also work with the USB host shield, however I don't have one to check.

Here's the PR in question:
https://github.com/gdsports/USB_Host_Library_SAMD/pull/12

I thought I'd post this here in case anyone comes looking for PS5 controller support, and in hopes that someone with the usb host shield and a PS5 controller could try copying in the new files and testing if it works.

### PR DESCRIPTION
**Pull request by Lauszus**
Fixes #567

### CODE REVIEW

**Comment by Lauszus** [comment]
@josephduchesne I have now added support for the controller via USB. It is more less the same as yours, but I fixed a couple of bugs and added support for the player and microphone LEDs.

**Comment by Lauszus** [comment]
@joseangeljimenez I've left a few comments on your PR: https://github.com/gdsports/USB_Host_Library_SAMD/pull/12/files

**Comment by Lauszus** [comment]
Bluetooth is now also working. However setting the LEDs etc still does not work.

**Comment by joseangeljimenez** [comment]
> @joseangeljimenez I've left a few comments on your PR: https://github.com/gdsports/USB_Host_Library_SAMD/pull/12/files

I think you meant to notice another person! Regards, Jose

**Comment by Lauszus** [comment]
> I think you meant to notice another person! Regards, Jose

Sorry about that. That was indeed a typo. Thanks for letting me know :)

I was supposed to tag @josephduchesne.

**Comment by josephduchesne** [comment]
I'll have to go through this line-by-line to port your port back to my version with all of the fixes and improvements :) The joys of open source big forks.

**Comment by Lauszus** [comment]
> I'll have to go through this line-by-line to port your port back to my version with all of the fixes and improvements :) The joys of open source big forks.

Awesome :)

Note that I disabled parsing the status for now, as it's different for USB and Bluetooth: https://github.com/felis/USB_Host_Shield_2.0/pull/585/commits/fdb0ee31e79debd2f807996a7554177212404aa0

**Pull request merged**
